#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 人类身高
name_en: Study of Human Height

# Short bio or description (displayed in the header)
description: 收集、分析人类身高数据
description_en: Collecting and analyzing human height data

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Timezone -- important for correct date!
timezone: Asia/Shanghai

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    name_en: Home
    url: /
  - name: 作者
    name_en: Authors
    url: /authors.html
  - name: 栏目
    name_en: Categories
    url: /categories.html
  - name: 标签
    name_en: Tags
    url: /tags.html
  - name: 关于
    name_en: About
    url: /about.html

# Pagination
paginate: 20

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: renleishengao@protonmail.com
  facebook:
  flickr:
  github: renleishengao/renleishengao.github.io
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  telegram:
  pinterest:
  rss: feed.xml # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: 
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: 纪念 <a href="/about.html#声援蔡伟">TerminusBot</a>

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://rlsg.xyz/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: /terminus-jekyll-template

        #sampaths:
        #display_name: Sampath Sirimane
        #about: Sampath is a blogger, story and novel writer for a damous daily news paper.
        #email: mailto: sirimane@gmail.com
        #web: http://samapathsirimane.com
        #facebook: https://www.facebook.com/sirimane.sampath
        #twitter: https://twitter.com/sirimane
        #github: https://github.com/sirimane/
        #gravatar: https://raw.githubusercontent.com/sharu725/lanyon/gh-pages/public/img/samapths.jpg       

# allow future posts
# future: true

#
# !! You don't need to change any of the configuration flags below !!
#

# permalink: /:title/
# paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v3.8.4

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

strict_front_matter: true

liquid:
  error_mode: strict

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
